env:
    browser: true
    es2021: true
    node: true
extends:
    - standard
parserOptions:
    ecmaVersion: 2020
    sourceType: module
rules:
    max-len:
        - 'error'
        - code: 80
          tabWidth: 4
          comments: 80
    indent:
        - error
        - 2
    no-multiple-empty-lines:
        - 'off'
    comma-dangle:
        - error
        - only-multiline
    padded-blocks:
        - off
    spaced-comment:
        - off
    no-multi-spaces:
        - error
        - ignoreEOLComments: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
